const { Blog } = require('../models');

const blogData = [
	{
		title: 'Creating a website',
			contents: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse tristique mauris in sollicitudin condimentum. Nunc malesuada justo nec dignissim consectetur. Aliquam interdum leo consectetur mi imperdiet semper a ut sapien. Nulla vehicula euismod nibh, a egestas eros. Nullam nec consectetur neque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi risus eros, feugiat id erat a, pharetra facilisis quam. Sed et tellus turpis. Aliquam justo dui, fringilla ac vehicula mollis, molestie eu erat. Quisque commodo ut odio vel sagittis. Phasellus sit amet nibh sed lectus pretium vulputate. Curabitur mattis velit id aliquet aliquet. Donec tincidunt sollicitudin massa, eget porta justo imperdiet et. Etiam sit amet tincidunt urna. Vivamus a est mauris. Sed ac feugiat arcu.\nAliquam in mi eget eros fringilla interdum.Suspendisse laoreet in nisi ac dignissim.Curabitur ac turpis at diam rhoncus accumsan ac eget dui.Donec porta quam leo, eget porttitor ligula tincidunt eget.Suspendisse turpis metus, lacinia ac leo vitae, egestas faucibus erat.Sed eget sapien in sapien commodo sagittis ac at ex.Pellentesque suscipit, lectus sit amet varius fermentum, est est bibendum massa, et ullamcorper purus felis eget arcu.In hac habitasse platea dictumst.Morbi malesuada fringilla convallis.Ut id feugiat sem.Mauris eu velit in nunc tincidunt lacinia sed sed urna.Suspendisse tristique est sed turpis semper luctus s\nFusce at venenatis metus.Sed lectus quam, tempor a finibus nec, imperdiet non libero.Nullam augue lorem, lacinia quis semper consectetur, commodo in mi.Integer blandit interdum condimentum.Maecenas hendrerit diam purus, quis lacinia sem scelerisque euismod.Phasellus commodo posuere turpis, sed condimentum lectus blandit sed.Sed auctor molestie ipsum, et mollis purus aliquet sed.Mauris sodales nisi eget dui interdum commodo.Sed sed congue nisl, ac auctor arcu.Integer nec diam suscipit, eleifend urna in, accumsan tellus.',
		user_id: 1,
	},
	{
		title: 'How to use nodemon',
		contents: 'Aliquam congue tellus ac maximus iaculis. Praesent pulvinar non odio pretium dignissim. Donec interdum, augue sit amet imperdiet ultricies, ante ante tempor massa, in rhoncus lectus mauris a tellus. Phasellus bibendum arcu ut lacus congue, sit amet venenatis velit commodo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent luctus laoreet tellus vitae placerat. Sed feugiat tellus ligula, sit amet bibendum nunc semper ut. Aliquam lectus dolor, convallis at nibh eu, tincidunt vestibulum eros. Ut eget purus at enim egestas vulputate non sodales sapien. Ut vitae nibh arcu. Nullam aliquam tristique eros, id luctus quam pretium sed. Duis a venenatis nulla, ut imperdiet nisl. Fusce mattis, libero ac pharetra feugiat, quam metus pulvinar odio, eu placerat ipsum ante vitae risus.\nNulla at enim lorem.Morbi vulputate finibus lacus.Vivamus tempus sem eros, nec mattis ipsum interdum sed.Praesent tortor turpis, facilisis a enim eget, imperdiet ultrices elit.In et cursus arcu.Pellentesque turpis erat, convallis cursus consectetur non, mollis id nisi.Fusce nec fringilla ex.Nam convallis at libero id porttitor.Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut egestas pharetra nulla.Nam feugiat faucibus ligula, ac ultrices risus.Vivamus interdum aliquet libero.Etiam pharetra tristique lorem sit amet tempus.Morbi commodo vel est non tristique.Quisque a massa feugiat, placerat libero vel, auctor felis.',
		user_id: 3,
	},
];

const seedBlog = () => Blog.bulkCreate(blogData);

module.exports = seedBlog;
